### ISSUE TITLE
Modal animations Update Mode should use unscaled time.

### ISSUE THREAD

**Issue by m4rkk** [siberder/UnityModalWindows#4]
It is common to set Time.timeScale=0 to halt gameplay and then set it back to 1 to continue. However, non gameplay animations in UI will also be halted unless the Update Mode of these animation is set to unscaled time.

**Comment by siberder** [comment]
Great note :)
Feel free to open PR!
Unless I will eventually get to this little issue :)

**Comment by m4rkk** [comment]
Charging toward a release so I took the lazy way out for now =) Love this little project of yours btw!

**Comment by siberder** [comment]
Thanks for the heartwarming words and best of luck with your release!
