### ISSUE TITLE
when i pause game "Time.timeScale = 0;" modal windows freezes

### ISSUE THREAD

**Issue by MrFlanker** [siberder/UnityModalWindows#6]
I want to pause game when use this modal windows.... but when i use
`Time.timeScale = 0`
modal windows also freezes. I think it there animation.

A there easy way yo solve this problem ?

**Comment by siberder** [comment]
Hello!

Inside folder _Resources/Modal Windows_ find _SimpleModalWindow_ prefab and on the **Animator** component look for **Update Mode** option and select **Unscaled Time**. Like this:
![image](https://github.com/siberder/UnityModalWindows/assets/32988397/4a9f10c3-f21d-447e-a5eb-fdb15f980ffa)
